version: '3.8'

services:
  maple:
    build:
      context: .
      dockerfile: Dockerfile # Assuming your Dockerfile is named 'Dockerfile'
    ports:
      - '8080:80' # Maps port 80 from the container to 8080 on your host
    restart: unless-stopped
